#
# CircleCI configuration for phone-picker
#

version: 2
jobs:
  setup:
    working_directory: ~/phone-picker
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/phone-picker-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn install --silent
      - save_cache:
          key: ~/phone-picker-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    working_directory: ~/phone-picker
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/phone-picker-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn test

  build:
    working_directory: ~/phone-picker
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/phone-picker-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn build
      - save_cache:
          key: dist-{{ .Revision }}
          paths:
            - build


workflows:
  version: 2
  test_and_build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
